#!/bin/sh

# Color
sed -i "27s/.*/theme = themes[2]/g" ~/.config/awesome/rc.lua
xrdb /home/katsuki/.Xresources_dark

sed -i "11s/light/dark/g" $HOME/.config/rofi/clean.rasi

# sed -i "35s/light/dark/g" $HOME/.mozilla/firefox/ra41gmx6.default-release-1646229770928/chrome/userChrome.css

# Gtk
# sed -i "2s/.*/gtk-icon-theme-name=Mkos-Big-Sur-Night/g" ~/.config/gtk-3.0/settings.ini
# sed -i "4s/.*/gtk-theme-name=WhiteSur-dark/g" ~/.config/gtk-3.0/settings.ini

# Picom
# sed -i "7s/.*/shadow-opacity = 0.4;/g" ~/.config/awesome/config/picom.conf

# Spotify
# spicetify config color_scheme dark
# spicetify update
